### ISSUE TITLE
mount  in entrypoint does not work in all environment

### ISSUE THREAD

**Issue by Breee** [DependencyTrack/frontend#513]
### Current Behavior

Given the following kubernetes deployment: 

```
metadata:
  name: dependencytrack-dev-frontend
  namespace: dependencytrack-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dependencytrack
      component: frontend
      stage: dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: dependencytrack
        component: frontend
        stage: dev
    spec:
      containers:
      - image: dependencytrack/frontend:4.8.1
        imagePullPolicy: Always
        name: dependencytrack-dev-frontend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsUser: 101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/localtime
          name: tz-config
        - mountPath: /opt/owasp/dependency-track-frontend/static/config.json
          name: static-config
          subPath: config.json
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: tmp
      - hostPath:
          path: /usr/share/zoneinfo/UTC
          type: ""
        name: tz-config
      - configMap:
          defaultMode: 420
          items:
          - key: config.json
            path: config.json
          name: dependencytrack-dev-static-config
        name: static-config
```
and the following configmap: 

```
apiVersion: v1
data:
  config.json: |-
    {
      "OIDC_ISSUER": "xxxxxxxxxxx",
      "OIDC_CLIENT_ID": "xxxxxxxxxxxxxxxxx",
      "OIDC_SCOPE": "openid profile email",
      "OIDC_FLOW": "",
      "OIDC_LOGIN_BUTTON_TEXT": "Login with Azure AD",
      "API_BASE_URL": "https://api.dependencytrack-dev.xxxxxxxxxxx"
    }
kind: ConfigMap
```

I experience the following logs: 

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-oidc-configuration.sh
mv: can't remove './static/config.json': Resource busy
```

however:  

if i look at `/proc/mounts` in the running container i can clearly see mounts: 

```
$ cat /proc/mounts
overlay / overlay rw,relatime,lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/277/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/276/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/130/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/127/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/126/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/125/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/124/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/123/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/122/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/121/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/120/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/119/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/76/fs,upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/279/fs,workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/279/work,xino=off 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev tmpfs rw,nosuid,size=65536k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs rw,nosuid,nodev,noexec,relatime,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/rdma cgroup ro,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
/dev/sda1 /tmp ext4 rw,relatime,errors=remount-ro 0 0
/dev/sda1 /etc/localtime ext4 rw,relatime,errors=remount-ro 0 0
/dev/sda1 /etc/hosts ext4 rw,relatime,errors=remount-ro 0 0
/dev/sda1 /dev/termination-log ext4 rw,relatime,errors=remount-ro 0 0
/dev/sda1 /etc/hostname ext4 rw,relatime,errors=remount-ro 0 0
/dev/sda1 /etc/resolv.conf ext4 rw,relatime,errors=remount-ro 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
/dev/sda1 /opt/owasp/dependency-track-frontend/static/config.json ext4 ro,relatime,errors=remount-ro 0 0
proc /proc/bus proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/fs proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/irq proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sys proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sysrq-trigger proc ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /proc/acpi tmpfs ro,relatime 0 0
tmpfs /proc/kcore tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/keys tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/timer_list tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/sched_debug tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/scsi tmpfs ro,relatime 0 0
tmpfs /sys/firmware tmpfs ro,relatime 0 0
```

This happens because `mount` in https://github.com/DependencyTrack/frontend/blob/master/docker/docker-entrypoint.sh#L6 
returns an empty string, which leads to entering the else case.  

We are using: 
- Kubernetes 1.27.2
- Containerd 1.7.2 

The mount command works fine in the `nginxinc/nginx-unprivileged` container itself, but not in the container built with https://github.com/DependencyTrack/frontend/blob/master/docker/Dockerfile.alpine

That leads me to the conclusion that something in the dockerfile is not right. 

I also tested against upstream

### Steps to Reproduce

1. Deploy Dependency Track frontend to k8s 
2. Investigate the logs 
3. Override the command  to `/bin/sh -c`  and the args to `while true; do sleep 100; done` to avoid the crashing container
4. Execute kubectl exec <dependency-track-pod> -- mount   and see that nothing is returned compared to other pods.

### Expected Behavior

mount command should work

### Dependency-Track Frontend Version

4.8.1

### Browser

Google Chrome

### Browser Version

-

### Operating System

Linux

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported
